rules:
  property-sort-order:
    - 2
    -
      order: 'recess'
  indentation:
    - 2
    -
      size: 2
  nesting-depth:
    - 2
    -
      max-depth: 4
  force-pseudo-nesting:
    - 0
  no-color-literals:
    - 0
